PROD = "engine/server/data/source_fetch.py"
TEST = "tests/active/test_source_fetch.py"

MUTATIONS = [
    ("A-offhost-followed", 'parts.scheme == "https" and parts.hostname == host and port', 'parts.scheme == "https" and port',
     "redirect_handler_refuses or fetch_names_a_refused_redirect or stream_media_keeps_todays_text or refused_redirect_does_not_carry"),
    ("B-refused-unrecorded", "            self.refused = newurl\n", "",
     "redirect_handler_refuses or fetch_names_a_refused_redirect"),
    ("B2-shared-handler", "    handler = SameHostRedirectHandler(host)\n    chunks", '    handler = globals().setdefault("_SHARED", {}).setdefault(host, SameHostRedirectHandler(host))\n    chunks',
     "refused_redirect_does_not_carry"),
    ("C-same-host-not-followed", "        return super().redirect_request(req, fp, code, msg, headers, newurl)", "        return None",
     "redirect_handler_follows or fetch_follows_a_same_host_redirect or stream_media_follows_a_same_host_redirect"),
    ("D1-raised-status-unnamed", 'else f"HTTP {exc.code}")', 'else "HTTP error")',
     "fetch_names_the_status"),
    ("D2-returned-status-unnamed", '                raise SourceFetchFailed(f"HTTP {resp.status}")', '                raise SourceFetchFailed("HTTP error")',
     "fetch_names_the_status"),
    ("E-declared-length-unchecked", '            if length.isdigit() and int(length) > max_bytes:\n                raise SourceFetchFailed(f"Content-Length', '            if False:\n                raise SourceFetchFailed(f"Content-Length',
     "declared_length_over_the_cap or max_bytes_override"),
    ("F1-cap-off-by-one", '                if size > max_bytes:\n                    raise SourceFetchFailed(f"body over', '                if size >= max_bytes:\n                    raise SourceFetchFailed(f"body over',
     "body_of_2_000_000_bytes_whole"),
    ("F2-cap-checked-after-reading", '                size += len(chunk)\n                if size > max_bytes:\n                    raise SourceFetchFailed(f"body over {max_bytes} bytes")\n                chunks.append(chunk)',
     '                size += len(chunk)\n                chunks.append(chunk)\n            if size > max_bytes:\n                raise SourceFetchFailed(f"body over {max_bytes} bytes")',
     "streamed_past_the_cap_reading_no_further"),
    ("G-deadline-unchecked", '                if time.monotonic() > deadline:\n                    raise SourceFetchFailed("deadline passed")\n', "",
     "deadline_passed_while_the_body or deadline_is_8_seconds or deadline_seconds_override"),
    ("H-budget-exactly-now-allowed", "    if remaining <= 0:", "    if remaining < 0:",
     "budget_spent"),
    ("I-deadline-9s", "FETCH_DEADLINE_SECONDS = 8.0", "FETCH_DEADLINE_SECONDS = 9.0",
     "deadline_is_8_seconds"),
    ("J-open-error-text-lost", "raise SourceFetchFailed(str(exc) or type(exc).__name__) from exc", "raise SourceFetchFailed(type(exc).__name__) from exc",
     "fetch_names_an_error_raised_at_open"),
    ("K-accept-header", 'else {"accept": "application/json, text/vtt"}', 'else {"accept": "application/json"}',
     "sends_todays_accept_header"),
    ("K2-socket-timeout-uncapped", "_open(request, handler, min(socket_timeout, remaining))", "_open(request, handler, socket_timeout)",
     "sends_todays_accept_header or socket_timeout_override"),
    ("K3-socket-timeout-5s", "SOCKET_TIMEOUT_SECONDS = 4.0", "SOCKET_TIMEOUT_SECONDS = 5.0",
     "sends_todays_accept_header"),
    ("L-headers-merged", 'headers=headers if headers is not None else {"accept": "application/json, text/vtt"}', 'headers={"accept": "application/json, text/vtt", **(headers or {})}',
     "headers_override"),
    ("M-deadline-seconds-ignored", "remaining = deadline_seconds if budget_at is None else min(deadline_seconds, budget_at - now)", "remaining = FETCH_DEADLINE_SECONDS if budget_at is None else min(FETCH_DEADLINE_SECONDS, budget_at - now)",
     "deadline_seconds_override"),
    ("N-socket-timeout-ignored", "_open(request, handler, min(socket_timeout, remaining))", "_open(request, handler, min(SOCKET_TIMEOUT_SECONDS, remaining))",
     "socket_timeout_override"),
    ("O-max-bytes-ignored", "    now = time.monotonic()\n    # remaining first", "    now = time.monotonic()\n    max_bytes = FETCH_MAX_BYTES\n    # remaining first",
     "max_bytes_override"),
    ("P-media-socket-timeout-8s", "MEDIA_SOCKET_TIMEOUT_SECONDS = 15.0", "MEDIA_SOCKET_TIMEOUT_SECONDS = 8.0",
     "stream_media_feeds_the_whole_body"),
    ("Q-media-status-text", '                raise SourceFetchFailed(f"media download failed: HTTP {resp.status}")', '                raise SourceFetchFailed(f"HTTP {resp.status}")',
     "stream_media_names_a_non_200"),
    ("R-media-error-text", 'raise SourceFetchFailed(f"media download failed: {exc}") from exc', 'raise SourceFetchFailed(f"media download failed: {type(exc).__name__}") from exc',
     "stream_media_names_an_error_raised_at_open or stream_media_keeps_todays_text or broken_pipe"),
    ("S-media-declared-length-unchecked", '            if length.isdigit() and int(length) > max_bytes:\n                raise SourceFetchFailed(f"media over', '            if False:\n                raise SourceFetchFailed(f"media over',
     "stream_media_refuses_a_declared_length or stream_media_names_its_own_max_bytes"),
    ("T-media-consumed-before-cap", '                size += len(chunk)\n                if size > max_bytes:\n                    raise SourceFetchFailed(f"media over {max_bytes} bytes")\n                consume(chunk)',
     '                consume(chunk)\n                size += len(chunk)\n                if size > max_bytes:\n                    raise SourceFetchFailed(f"media over {max_bytes} bytes")',
     "stream_media_refuses_a_body_streamed_past or stream_media_names_its_own_max_bytes"),
    ("U-stop-ignored", "            while not stop.is_set():", "            while True:",
     "once_stop_is_set"),
    ("V-broken-pipe-wrapped", "    except BrokenPipeError:\n        # The consumer's pipe closed, not the download; an OSError, so it must pass before the tuple below.\n        raise\n", "",
     "broken_pipe"),
    ("W-media-host-normalized", "    return host if len(labels)", "    return normalize_host(host) if len(labels)",
     "media_host_returns_the_raw"),
    ("X-media-host-tld-unchecked", " and _TLD.fullmatch(labels[-1]) else None", " else None",
     "media_host_refuses"),
]
