"""Claude Code over an Anthropic subscription: the `oauth:anthropic` issuer, and a
provider that shapes each request the way the Claude Code client does.

`un.plugins.stock.oauth` is the mechanism and names no issuer; this file is one issuer's
worth of data plus the request adaptation that makes the subscription endpoint accept
what un sends.
Nothing in un imports this - it arrives through the `un.plugins` entry-point group and
stays off until `enable_plugin` in `.un/config.toml` names it.

# rat-tail: every pin is fixed to one Claude Code version rather than negotiated. There is
# no handshake to negotiate against, so drift surfaces as a 4xx from the endpoint. The
# upgrade path is `extract_claude_client.py`, which re-reads the installed binary and
# rewrites `client.toml`; this module holds no fallback copy of any pin.

Reads: `client.toml`, beside this file, at import.
Writes: nothing directly. `un.plugins.stock.oauth.save` writes
`.un/oauth/anthropic.credentials.json`.
"""

from __future__ import annotations

import getpass
import hashlib
import json
import platform
import sys
import tomllib
import uuid
from pathlib import Path

import anthropic

from un import CacheSpec, Profile, Reply, fold_system, providers, service, warn_spoofable
from un.core import project_root
from un.plugins.stock.oauth import Client, token

UN_PLUGIN = {"description": "Anthropic OAuth issuer and Claude Code request adaptation"}

# Every pinned value lives in `client.toml` beside this file, read once at import. They were read out of the
# INSTALLED Claude Code binary rather than from any writeup: the published research this plan started from
# described a DIFFERENT client, carrying `anthropic-client-version`, an `x-stainless-*` block spelling
# `js`/`node`, and `anthropic-client-platform: desktop_app`, none of which the CLI sends.
#
# The file is GENERATED by `extract_claude_client.py`, so a drifted pin is re-derived by running that against
# the installed binary instead of by editing Python. Nothing here carries a fallback value: two sources for one
# pin is how a stale constant goes on being sent long after the config was fixed.
CONFIG = Path(__file__).with_name("client.toml")

# Every key `[client]` must carry, with the type each is read as. Checked as a set at import rather than at the
# point of use, because a missing pin reaches the endpoint as a malformed request whose 4xx names the version
# and not the field - the same failure mode as sending a stale one, and no easier to read.
_PINS: dict[str, type] = {
    "code_version": str, "entrypoint": str, "client_platform": str, "max_output_tokens": int,
    "fingerprint_salt": str, "fingerprint_indices": list, "fingerprint_digest_length": int,
    "billing_prefix": str, "cch_placeholder": str, "marker": str, "betas": list,
}


def _client() -> dict:
    """`[client]` out of `client.toml`, every pin present and of the right type.

    RAISES rather than falling back. `core._refuse` catches this and prints
    `claude_subscription: refused, RuntimeError: ...` to stderr, which is a line naming the file and the repair -
    where a silent default would send a wrong pin and surface as a 4xx naming neither.
    """
    try:
        with CONFIG.open("rb") as handle:
            table = tomllib.load(handle).get("client")
    except OSError as exc:
        raise RuntimeError(f"cannot read {CONFIG}: {exc}. Run extract_claude_client.py to regenerate it") from exc
    except tomllib.TOMLDecodeError as exc:
        raise RuntimeError(f"{CONFIG} is not valid TOML: {exc}. Run extract_claude_client.py to regenerate it") from exc
    if not isinstance(table, dict):
        raise RuntimeError(f"{CONFIG} carries no [client] table. Run extract_claude_client.py to regenerate it")
    if wrong := sorted(name for name, kind in _PINS.items() if not isinstance(table.get(name), kind)):
        raise RuntimeError(f"{CONFIG} [client] is missing or mistyped: {', '.join(wrong)}. "
                           f"Run extract_claude_client.py to regenerate it")
    return table


_CLIENT = _client()

CODE_VERSION = _CLIENT["code_version"]
ENTRYPOINT = _CLIENT["entrypoint"]
CLIENT_PLATFORM = _CLIENT["client_platform"]
MAX_OUTPUT_TOKENS = _CLIENT["max_output_tokens"]
FINGERPRINT_SALT = _CLIENT["fingerprint_salt"]
# Tuples, because both are read positionally and a list read from TOML is mutable: a caller that appended to
# either would change what every later request sends, silently.
FINGERPRINT_INDICES = tuple(_CLIENT["fingerprint_indices"])
FINGERPRINT_DIGEST_LENGTH = _CLIENT["fingerprint_digest_length"]
BILLING_PREFIX = _CLIENT["billing_prefix"]
CCH_PLACEHOLDER = _CLIENT["cch_placeholder"]
MARKER = _CLIENT["marker"]
BETAS = tuple(_CLIENT["betas"])

# `claude-cli/<version> (external, <entrypoint>)`. The parenthetical takes optional
# `, agent-sdk/...`, `, client-app/...` and `, workload/...` segments, each present only
# when its environment variable is set - a plain CLI run emits none of them.
USER_AGENT = f"claude-cli/{CODE_VERSION} (external, {ENTRYPOINT})"

# The claude.ai authorize host grants these five and NOT `org:create_api_key`, which
# belongs to the console host's set. Asking claude.ai for it is refused as an invalid
# request format - observed, then confirmed against a captured browser session, where the
# authorize page's own POST carries exactly these five and silently drops the sixth.
#
# A subscription is what this plugin is for, so the console scope buys nothing anyway:
# `user:inference` is the one that pays for a request.
SCOPES = (
    "user:profile",
    "user:inference",
    "user:sessions:claude_code",
    "user:mcp_servers",
    "user:file_upload",
)

CLIENT = Client(
    name="anthropic",
    # PUBLIC client metadata, and only that. The Authorization Code flow with PKCE has no
    # client secret, and the operator's own token lives in `.un/oauth/`, never here.
    client_id="9d1c250a-e61b-44d9-88ed-5944d1962f5e",
    # `code=true` is REQUIRED and is not a parameter the mechanism models. It rides here
    # because `oauth.authorize_url` merges an issuer's own query rather than replacing it -
    # which is exactly the case that provision was written for. Without it the authorize
    # page refuses the request as malformed.
    authorize_url="https://claude.com/cai/oauth/authorize?code=true",
    token_url="https://platform.claude.com/v1/oauth/token",
    # A LOOPBACK redirect, so `oauth.localhost_port` returns the port and `un login` takes
    # its listener branch. The manual paste-back URI
    # (`platform.claude.com/oauth/code/callback`) exists in the client but is its fallback,
    # and this issuer refuses it as an invalid request format - observed against the real
    # authorize page, then confirmed against a captured Claude Code login, which called
    # back to `http://localhost:<port>/callback`.
    #
    # rat-tail: the port is FIXED where the reference client binds a random free one. A
    # `Client` names its redirect before the flow starts, and the redirect has to match
    # what the issuer is told, so a random port needs a Client built per login rather than
    # a constant. The upgrade path, if 54545 is ever taken on a real machine, is an
    # `oauth:` service that binds a socket first and builds its Client around that port.
    redirect_uri="http://localhost:54545/callback",
    scope=" ".join(SCOPES),
    # This endpoint takes `application/json` and refuses a form-encoded body, which RFC
    # 6749 section 4.1.3 specifies. The field set is identical; only the encoding differs.
    token_json=True,
    # The token endpoint sits behind Cloudflare, which refuses urllib's default
    # `Python-urllib/<version>` with a 403 "Error 1010: Access denied" - a rejection of the
    # CLIENT that says nothing about the request. The same user-agent the inference calls
    # send, so the two halves of this plugin identify themselves identically.
    user_agent=USER_AGENT,
)


@service("oauth:anthropic")
def issuer() -> Client:
    """the Anthropic subscription a Claude plan covers"""
    return CLIENT


# --- the six Claude Code request adaptations ------------------------------------------

def headers() -> dict[str, str]:
    """The identity block the CLI sets for itself, and nothing more.

    THREE headers. The writeup this plan started from listed a dozen, including an
    `x-stainless-*` block and `anthropic-client-version`; reading the installed binary
    shows the CLI sets none of those. `x-stainless-*` is generated by whichever Anthropic
    SDK is making the call, and spelling it by hand said `lang: js, runtime: node` while a
    PYTHON SDK sent the request - a contradiction visible to anything inspecting the pair,
    and a plausible reason for a client-level rejection. Left alone, the SDK sends the
    truth about itself.

    `anthropic-beta` is absent DELIBERATELY for a different reason: the betas ride `betas=`
    on the request so `output_config` keeps working, and the SDK renders the same header
    from them. Setting both would be two sources for one header.
    """
    return {
        "user-agent": USER_AGENT,
        "x-app": "cli",
        "anthropic-client-platform": CLIENT_PLATFORM,
    }


def first_user_text(messages: list[dict]) -> str:
    """The text of the FIRST user message: the billing fingerprint's seed.

    The FIRST text block, not every text block joined. The reference does `content.find(
    b => b.type === "text")` and returns that one block's text, so a message carrying two
    text blocks contributes only the first - and since the fingerprint reads characters at
    positions 4, 7 and 20, joining would silently seed it from different characters.

    A non-text block before the first text one is skipped rather than ending the search,
    which is what makes an image-then-text message seed from its text.
    """
    for message in messages:
        if message.get("role") != "user":
            continue
        content = message.get("content")
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            return next((block["text"] for block in content
                         if isinstance(block, dict) and block.get("type") == "text"
                         and isinstance(block.get("text"), str)), "")
        return ""
    return ""


def billing_header(first_user: str) -> str:
    """The `x-anthropic-billing-header` text that becomes system[0].

    `cch=00000` goes out as written; see `CCH_PLACEHOLDER`. An index past the end of the
    message contributes "0", matching the reference's `e[y]||"0"` - padding, never
    truncation, or a short first message would produce a seed of the wrong length.
    """
    seed = "".join(first_user[i] if i < len(first_user) else "0"
                   for i in FINGERPRINT_INDICES)
    suffix = hashlib.sha256(
        f"{FINGERPRINT_SALT}{seed}{CODE_VERSION}".encode()).hexdigest()[:FINGERPRINT_DIGEST_LENGTH]
    return (f"{BILLING_PREFIX} cc_version={CODE_VERSION}.{suffix}; "
            f"cc_entrypoint={ENTRYPOINT}; {CCH_PLACEHOLDER};")


def _device_seed() -> str:
    """A machine-stable seed. `getuser` raises where there is no passwd entry."""
    try:
        return f"{platform.node()}:{getpass.getuser()}:{Path.home()}"
    except Exception:  # noqa: BLE001 - any lookup failure is the same fallback
        return f"{platform.node()}:claude-oauth-fallback"


DEVICE_ID = hashlib.sha256(
    f"claude-oauth-device-v1:{_device_seed()}".encode()).hexdigest()
# Per process, which is what a CLI can honestly claim: one `un` invocation is one session.
SESSION_ID = str(uuid.uuid4())


def user_id() -> str:
    """The `{device_id, session_id}` envelope sent as `metadata.user_id`.

    Separators are tightened to match `JSON.stringify`, which emits no spaces. The value
    is opaque to un but not necessarily to the endpoint.
    """
    return json.dumps({"device_id": DEVICE_ID, "session_id": SESSION_ID},
                      separators=(",", ":"))


def system_blocks(system: str, messages: list[dict], *, stable: bool) -> list[dict]:
    """The three system blocks the endpoint expects, in order.

    [0] the billing header, [1] the Claude Code identity marker, [2] un's own prompt. The
    marker sits at [1] rather than [0] because the billing block is unshifted in front of
    it, which is the reference client's shape.

    ONE breakpoint, on the LAST block, so the tool schemas and the whole system prefix
    cache together - `anthropic_provider` places it the same way and for the same reason.
    """
    blocks = [
        {"type": "text", "text": billing_header(first_user_text(messages))},
        {"type": "text", "text": MARKER},
        {"type": "text", "text": system},
    ]
    if stable:
        # `ttl` is the extended retention the OAuth beta allows; without it the
        # breakpoint is standard retention, which is a quieter and more expensive bug.
        blocks[-1]["cache_control"] = {"type": "ephemeral", "ttl": "1h"}
    return blocks


# --- the provider service -------------------------------------------------------------


def _emit(sink, channel: str, text: str) -> None:
    """Push to the caller's sink if there is one. Headless runs pass None."""
    if sink is not None:
        sink(channel, text)


# The SDK sets `User-Agent` itself, and `default_headers` MERGES by key rather than
# replacing - httpx then joins duplicates with ", ", so a lowercase `user-agent` appends
# instead of overriding and the request goes out as:
#
#     user-agent = Anthropic/Python 0.125.0, claude-cli/2.1.251 (external, cli)
#
# announcing two clients at once, silently. Observed on anthropic 0.125.0. Matching the
# SDK's own casing makes it replace. `x-app` and `anthropic-client-platform` have no
# SDK-set twin, so they need no entry.
_SDK_CASED = {"user-agent": "User-Agent"}


def sdk_headers() -> dict[str, str]:
    """`headers()`, keyed so the SDK REPLACES its own rather than appending to them.

    Separate from `headers()` because the two answer different questions: `headers()` is
    the identity block this client sends, spelled the way the client spells it, and this
    is that block keyed for one particular SDK's merge.
    """
    return {_SDK_CASED.get(name, name): value for name, value in headers().items()}


def _client_for(profile: Profile) -> anthropic.Anthropic:
    """The client this profile pays with: an OAuth bearer, not an API key.

    `token` refreshes on read, so an expired credential never reaches an Authorization
    header. It raises `NotAuthorized` - a `ProviderError` - so a missing credential reaches
    the operator as one line naming `un login` rather than as a 401 naming nothing.

    No `base_url`: the SDK falls back to ANTHROPIC_BASE_URL and then to the real endpoint,
    so a stand-in endpoint needs no argument threaded through this file. No `http_client`
    either - the SDK's own is fine now that nothing rewrites the serialized body.

    Built per call rather than cached. `anthropic_provider` caches its client because the
    SDK resolves the credential once at construction; here the credential is resolved by
    `token` on every call, which is what makes refresh-on-read work.
    """
    return anthropic.Anthropic(
        auth_token=token(CLIENT, project_root() or Path.cwd()),
        default_headers=sdk_headers(),
        max_retries=5,
    )


MISPLACED = "was handed operator text in a position the Messages API refuses"


def _system_misplaced(messages: list[dict]) -> bool:
    """Whether a `role: "system"` message sits where the Messages API refuses it.

    It must follow a user turn, must be last or be followed by an assistant turn, and must
    never be `messages[0]`. Any turn that ends before its assistant reply strands operator
    text this way - an interrupt, or a run stopping at `max_turns` - because `TurnStart`
    and `ToolResults` append it first and the next prompt lands behind it.

    A COPY of `anthropic_provider._system_misplaced`, deliberately. Importing that module
    runs its `register()` at import and would claim `provider:anthropic` from inside this
    plugin, and `un.core` - where a shared copy belongs - is operator-edited only. The
    rule is the Messages API's and is fixed, so the two copies have nothing to drift over.
    """
    for index, message in enumerate(messages):
        if message.get("role") != "system":
            continue
        if index == 0:
            return True
        after = messages[index + 1:index + 2]
        if after and after[0].get("role") != "assistant":
            return True
    return False


def call(profile: Profile, *, system: str, messages: list[dict], tools: list[dict],
         model: str, effort: str, cache: CacheSpec, emit=None) -> Reply:
    """One turn against the subscription endpoint, shaped like the Claude Code client."""
    caching = ({"cache_control": {"type": "ephemeral", "ttl": "1h"}}
               if cache.history_append_only else {})
    # This endpoint is the Messages API, so it refuses operator text a cut-short turn
    # stranded - an interrupt or a `max_turns` stop leaves a `role: "system"` message with
    # no assistant turn behind it, and the next prompt lands after it. Repaired from
    # POSITION before the request, the same way `anthropic_provider` does it: nothing can
    # rescue it by appending, and the 400 it would otherwise raise kills the session.
    if _system_misplaced(messages):
        # No remedy: no model choice affects a stranded message, so the advice a model
        # refusing the role gets would be unfollowable here.
        #warn_spoofable(model, emit, why=MISPLACED, remedy="")
        messages = fold_system(messages)
    with _client_for(profile).beta.messages.stream(
        model=model,
        # The clamp IS this constant: the Claude Code client sends no more, so there is
        # no larger value to reduce from.
        max_tokens=MAX_OUTPUT_TOKENS,
        # Here rather than in `headers()`, so `output_config` keeps working; the SDK
        # renders `anthropic-beta` from this list.
        betas=list(BETAS),
        # No `fallbacks="default"`, which `anthropic_provider` passes. That is a
        # claude-opus-5 feature - every other model answers
        # `'<model>' does not support the `fallbacks` parameter` with a 400 - and this
        # profile's model is the operator's choice, so the parameter cannot be assumed.
        # The `server-side-fallback` beta stays in BETAS because the installed client
        # sends it; the beta is advertised capability, the parameter is a request to use
        # it, and only the second is refused.
        system=system_blocks(system, messages, stable=cache.system_stable),
        tools=tools,
        messages=messages,
        metadata={"user_id": user_id()},
        output_config={"effort": effort},
        **caching,
    ) as stream:
        for event in stream:
            # Text only. The tool call is announced by `core.gate`, with its arguments;
            # announcing the bare name here as well put `Bash` above `Bash(command=...)` on
            # the operator's screen, where the first says nothing the second does not.
            if (event.type == "content_block_delta"
                    and event.delta.type == "text_delta"):
                _emit(emit, "text", event.delta.text)
        response = stream.get_final_message()

    # to_dict() once, on the way in, so the transcript and the next request handle exactly
    # one shape - the same move `anthropic_provider` makes and for the same reason.
    wire = response.to_dict()
    return Reply(content=wire["content"], stop_reason=response.stop_reason,
                 usage=wire["usage"])


def register(profiles) -> None:
    """Register one `provider:<name>` service per claude-code-adaptor loop profile.

    No implicit default, unlike `anthropic_provider.DEFAULT`. A STOCK plugin stands in when
    nothing claims its adaptor, because un has to work with no table at all; an AFTERMARKET
    one must claim only what the operator configured, or enabling it would change what an
    unrelated project talks to.

    Both halves of the filter matter. The adaptor says which wire format serves the
    profile, and it is the whole of the filter: every profile runs on un's own loop, so
    one naming this adaptor is one this plugin answers for.
    """
    for profile in [p for p in profiles if p.adaptor == "claude-code"]:
        def serve(*, system, messages, tools, model, effort, cache, emit=None,
                  _profile=profile):
            # `_profile` bound as a DEFAULT rather than closed over: a closure would
            # capture the loop variable and leave every registered service serving
            # whichever profile came last.
            return call(_profile, system=system, messages=messages, tools=tools,
                        model=model, effort=effort, cache=cache, emit=emit)

        # Read by `core.variants("provider")` for `un --help`, so it names the endpoint
        # rather than repeating the adaptor for every row.
        serve.__doc__ = (f"Claude Code subscription as {profile.name}"
                         + (f" ({profile.model})." if profile.model else "."))
        service(f"provider:{profile.name}")(serve)


# At import, against the project the process was launched in.
register(providers(project_root() or Path.cwd()))
